### ISSUE TITLE
Rerebase master (undo accidental history rewrite)

### ISSUE THREAD

**Issue by eMPee584** [fsfw-dresden/LiaScript-DevServer#1]
As discussed, an unintented history rewrite (of about 300 commits) happened here..
Steps to fix it:
- `git remote add LiaScript https://github.com/LiaScript/LiaScript-DevServer`
- `git fetch --all`
- `git checkout -b main-rerebase LiaScript/main`
- `git cherry-pick 4ee7c30^..7ce6ab4`

Which is what I did to end up with https://github.com/eMPee584/LiaScript-DevServer xD

**Comment by bastiion** [comment]
nice, can you make a PR so that I can merge it?

**Comment by eMPee584** [comment]
No, because if you merge it, it will not rewrite history again 😁..

you'll have to force push to recover original main.. or rename the main branch on the github web interface..

**Comment by eMPee584** [comment]
(Resolved, force-pushed 8f9538abed6934b18f887ae6582b9c272f835ef6 last week..)
